### ISSUE TITLE
Handle python dependencies in this repo

### ISSUE THREAD

**Issue by qiluo-msft** [Azure/sonic-mgmt-framework#78]
I notice this repo has implicit dependency on python wheels PyYAML and lxml during build.
https://github.com/Azure/sonic-buildimage/blob/7d02f799ef79d02e659fe1cfc70ae43a28c1bd7c/sonic-slave-buster/Dockerfile.j2#L412-L416

Please capture the dependency information in this repo, better to build the scripts (CLI/clitree/scripts) into a standalone wheel. And then the final deb package will use that wheel as a build dependency (not a runtime dependency).

I see lxml upgrades frequently. This way will make future life easier, no need to modify slave Dockerfile much.

**Comment by lguohan** [comment]
@ben-gale to check

**Comment by ben-gale** [comment]
> @ben-gale to check

@kwangsuk - pls check

**Comment by kwangsuk** [comment]
@qiluo-msft 
The scripts under CLI/clitree/scripts are used to parse, validate the XML files in CLI/clitree/cli-xml and generates the target XML files as output at the build time. The final debian package keeps the target XML files, but not scripts. So, I think it would not help much by making them into a wheel. Please advise me if you think otherwise. 
BTW, the above scripts has a dependency on lxml only. The pyYAML is used by pyang plugin to generate YAML files. That's a separate script under tools/pyang/pyang_plugins.

**Comment by qiluo-msft** [comment]
I see. It would be helpful you can list the build dependencies explicitly in README.
